### ISSUE TITLE
cant register users after updating to 1.1.15

### ISSUE THREAD

**Issue by NammariMarkavip** [intercom/intercom-android#181]
I can not register users after updating to sdk version 1.1.15 

log message 

Intercom-Android: ERROR: Failed to register or update user: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference

**Comment by harkin** [comment]
This should be fixed in 1.1.16, let us know if you see any issues with that version :+1:

**Comment by NammariMarkavip** [comment]
Its not fixed , I just tried version 1.1.16 and still the same issue

**Comment by harkin** [comment]
@NammariMarkavip Hm, I'd thought this might be related to us updating Okhttp, not so sure of that anymore. I can't reproduce this error locally. Can you try running our [sample app](https://github.com/intercom/intercom-android/tree/master/samples/intercom-androidstudio-sample) and let me know if that works for you?

**Comment by samehgerges** [comment]
we also still have this issue even after updating to 1.1.16. Our project has Retrofit 1.9.0, OKHttp 2.7.5 and Google play services 8.4.0 as dependencies as well

**Comment by ronocod** [comment]
@samehgerges can you try version 1.1.21? This should be fixed in that version.

**Comment by DaleCantwell** [comment]
@NammariMarkavip @samehgerges I'm to close out this issue, its fixed in version 1.1.21
Let us know if this occurs again in 1.1.21 and we will reopen.

**Comment by samehgerges** [comment]
Thank you guys it's working
