### ISSUE TITLE
NullPointerException in io.intercom.android.sdk.utilities.ContextLocaliser

### ISSUE THREAD

**Issue by christianlanz** [intercom/intercom-android#288]
## Version info
  - Intercom for Android version: 3.0.10
  - Android OS version: 4.1.2, 4.3 5.1.1, 6.0, 6.0.1, 7.0
  - Android Device: Sony XPERIA Z5 Compact, HUAWEI VNS-L21, SM-G920F, SM-A310F, GT-N8013, Sony Xperia XA, Nexus 5X, HTC One M9PLUS, SM-A510F, SM-G903F, LG-P710, Sony Xperia SP

## Expected behavior
Intercom messenger should start.

## Actual behavior
Runtime exception due an uncaught null pointer exception.

## Steps to reproduce
Caught via Crashlytics (fabrics.io)

## Logs
[crash.txt](https://github.com/intercom/intercom-android/files/591729/crash.txt)

**Comment by ronocod** [comment]
Thanks for reporting this, we're looking into this.

Posting stacktrace here for visibility:
```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'io.intercom.android.sdk.identity.AppIdentity io.intercom.android.sdk.Injector.getAppIdentity()' on a null object reference
       at io.intercom.android.sdk.utilities.ContextLocaliser.create(ContextLocaliser.java:27)
       at io.intercom.android.sdk.activities.IntercomBaseActivity.onCreate(IntercomBaseActivity.java:17)
       at io.intercom.android.sdk.activities.IntercomMessengerActivity.onCreate(IntercomMessengerActivity.java:64)
       at android.app.Activity.performCreate(Activity.java:6285)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2417)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2524)
       at android.app.ActivityThread.access$900(ActivityThread.java:154)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1391)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:234)
       at android.app.ActivityThread.main(ActivityThread.java:5526)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by ronocod** [comment]
Are you calling `Intercom.initialize()` in the `onCreate()` method of your `Application` class?

**Comment by christianlanz** [comment]
Yes, but there can be edge cases where we have to call `Intercom.initialize()` in `Activity.onCreate()`.

**Comment by ronocod** [comment]
In what case do you need to call it there? `Intercom.initialize()` should only be called in `Application.onCreate()`.

**Comment by christianlanz** [comment]
Due to an internal policy all external libraries must have a kill-switch, because of the crashes like this one. In that case the `Intercom.initialize()` is called when the user re-interacts with Intercom. Can you please fix the crash?

**Comment by ronocod** [comment]
Can you explain how this kill-switch works, and how the user is re-interacting with Intercom here?

We're working on a fix for this particular crash, but we only officially support initialisation in `Application.onCreate()`. We can't guarantee any support for other methods of initialisation, so we recommend you initialise there.

**Comment by christianlanz** [comment]
It's okay that you officially only support that way. But crashing is definitely not an excuse. Thanks for working on a fix.

**Comment by emmaguy** [comment]
We are seeing the same thing, but we don't call `initialize` twice. We have a dagger injected singleton wrapper around the intercom client as follows

```java
@Singleton
public class IntercomService {

    private final Application application;
    private Intercom client;

    @Inject
    public IntercomService(Application application) {
        this.application = application;
    }

    private synchronized Intercom getIntercomClient() {
        if (client == null) {
            Intercom.initialize(application, BuildConfig.INTERCOM_API_KEY, BuildConfig.INTERCOM_APP_ID);
            client = Intercom.client();
        }
        return client;
    }
```

**Comment by ronocod** [comment]
We'll have a fix in the next version to prevent this specific crash.

@emmaguy I'll look into how this state could be reached with your setup.

**Comment by emmaguy** [comment]
@ronocod do you have a rough ETA for the next version?

**Comment by ronocod** [comment]
@emmaguy should be today or tomorrow if all goes to plan.

**Comment by ronocod** [comment]
We've fixed this crash in 3.0.13, and we've also added in an explicit Exception which will be thrown when you try to open the Messenger when the SDK hasn't been initialised. If you experience this crash in 3.0.13 then please let us know, as that means there is an issue with the way `initialize()` is being called in your setup.

**Comment by shaibar** [comment]
@ronocod Hi this still happens to me on android version 4.4.2
i get the following error:
app launched, getComponentName:ComponentInfo {com.mypackage/io.intercom.android.sdk.activities.IntercomMessengerActivity}action:null

**Comment by ronocod** [comment]
@shaibar can you post the full stacktrace for this error?

**Comment by shaibar** [comment]
@ronocod It's working when i install the debug version and it crashes when i run the release version

**Comment by shaibar** [comment]
@ronocod Found the problem, never mind TNX :)
It's working great
Do you have an option to show the Messenger in small window in android ?

**Comment by ronocod** [comment]
@shaibar no, we only display full-screen on Android.
