### ISSUE TITLE
[CRASH] java.lang.RuntimeException

### ISSUE THREAD

**Issue by henrikra** [intercom/intercom-android#351]
## Version info
  - Intercom for Android version: 3.2.2
  - Android OS version: 7.1.1
  - Android Device: OnePlus ONEPLUS A3003

## Expected behavior
Not to crash
## Actual behavior
Crashed
## Steps to reproduce
If I try to guess from the logs I guess when admin is typing but animation is cancelled?

## Logs
```
java.lang.RuntimeException Could not dispatch event: class io.intercom.android.sdk.models.events.ConversationEvent to handler [EventHandler public void io.intercom.android.sdk.conversation.ConversationFragment.conversationSuccess(io.intercom.android.sdk.models.events.ConversationEvent)]: Attempt to invoke virtual method 'void io.intercom.android.sdk.views.AdminIsTypingView.cancelTypingAnimation()' on a null object reference 
    Bus.java:460 io.intercom.com.squareup.otto.Bus.throwRuntimeException
    Bus.java:387 io.intercom.com.squareup.otto.Bus.dispatch
    Bus.java:368 io.intercom.com.squareup.otto.Bus.dispatchQueuedEvents
    Bus.java:337 io.intercom.com.squareup.otto.Bus.post
    MainThreadBus.java:18 io.intercom.android.sdk.MainThreadBus.post
    CallbackHolder.java:111 io.intercom.android.sdk.api.CallbackHolder$6.onSuccess
    CallbackHolder.java:107 io.intercom.android.sdk.api.CallbackHolder$6.onSuccess
    BaseCallback.java:32 io.intercom.android.sdk.api.BaseCallback.onResponse
    ExecutorCallAdapterFactory.java:68 io.intercom.retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run
    Handler.java:751 android.os.Handler.handleCallback
    Handler.java:95 android.os.Handler.dispatchMessage
    Looper.java:154 android.os.Looper.loop
    ActivityThread.java:6290 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invoke
    ZygoteInit.java:886 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run
    ZygoteInit.java:776 com.android.internal.os.ZygoteInit.main


Caused: java.lang.NullPointerException Attempt to invoke virtual method 'void io.intercom.android.sdk.views.AdminIsTypingView.cancelTypingAnimation()' on a null object reference 
    NativeConversationContentPresenter.java:230 io.intercom.android.sdk.conversation.NativeConversationContentPresenter.onNewPartReceived
    ConversationFragment.java:635 io.intercom.android.sdk.conversation.ConversationFragment.conversationSuccess
    Method.java:-2 java.lang.reflect.Method.invoke
    EventHandler.java:89 io.intercom.com.squareup.otto.EventHandler.handleEvent
    Bus.java:385 io.intercom.com.squareup.otto.Bus.dispatch
    Bus.java:368 io.intercom.com.squareup.otto.Bus.dispatchQueuedEvents
    Bus.java:337 io.intercom.com.squareup.otto.Bus.post
    MainThreadBus.java:18 io.intercom.android.sdk.MainThreadBus.post
    CallbackHolder.java:111 io.intercom.android.sdk.api.CallbackHolder$6.onSuccess
    CallbackHolder.java:107 io.intercom.android.sdk.api.CallbackHolder$6.onSuccess
    BaseCallback.java:32 io.intercom.android.sdk.api.BaseCallback.onResponse
    ExecutorCallAdapterFactory.java:68 io.intercom.retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run
    Handler.java:751 android.os.Handler.handleCallback
    Handler.java:95 android.os.Handler.dispatchMessage
    Looper.java:154 android.os.Looper.loop
    ActivityThread.java:6290 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invoke
    ZygoteInit.java:886 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run
    ZygoteInit.java:776 com.android.internal.os.ZygoteInit.main
```

**Comment by ronocod** [comment]
Looking into this now

**Comment by ronocod** [comment]
This should be fixed in 3.2.4, can you try that version?

**Comment by henrikra** [comment]
I will try the updated version and if we still get the error I will reopen :)
