### ISSUE TITLE
Build fails on Android Studio 3.0-alpha2 (bad dimens)

### ISSUE THREAD

**Issue by adrien-aubel** [intercom/intercom-android#354]
With Gradle plugin 3.0-alpha2 and above, dimens with no unit are no longer supported, and Intercom contains such definition:
```
    <item format="float" name="intercom_faded_alpha_is_typing" type="dimen">0.4
    </item>
    <item format="integer" name="intercom_faded_is_typing_duration" type="dimen">200
    </item>
    <item format="float" name="intercom_full_alpha_is_typing" type="dimen">1.0
    </item>
```

It seems like those values shouldn't be declared as dimens anyway. So the fix should be as easy as moving them to a diferent XML, and making sure they're not declared with type `dimen`.

## Version info
  - Intercom for Android version: 3.2.3
  - Android OS version: -
  - Android Device: -

## Expected behavior
Project builds correctly

## Actual behavior
Resources merging fails

## Steps to reproduce
 1. Install Android Studio 3.0 Canary 2, with Gradle plugin 3.0-alpha2
 2. Build with Intercom
 3. Try to sync Gradle

## Logs

```
:app:mergeInviDevelopmentDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeInviDevelopmentDebugResources'.
> Error: java.lang.RuntimeException: com.android.builder.internal.aapt.AaptException: AAPT2 compile failed:
  aapt2 compile --no-crunch -o /Users/Adrien/Work/invi/android/app/build/intermediates/res/merged/inviDevelopment/debug /Users/Adrien/Work/invi/android/app/build/intermediates/incremental/mergeInviDevelopmentDebugResources/merged.dir/values/values.xml
  Issues:
   - ERROR: /Users/Adrien/Work/invi/android/app/build/intermediates/incremental/mergeInviDevelopmentDebugResources/merged.dir/values/values.xml:1625 invalid dimen

BUILD FAILED in 20s
```

## Temporary fix

To be able to build beside this issue, you can declare in your own resource this value (only integer dimens with no unit break at the moment):
```
    <dimen name="intercom_faded_is_typing_duration">200px</dimen>
```

**Comment by TapanM** [comment]
Same issue

**Comment by ronocod** [comment]
This will be fixed in the next release.

**Comment by mwajeeh** [comment]
Issue is in this line only `<item format="integer" name="intercom_faded_is_typing_duration" type="dimen">200
    </item>`
Other two float issues can be solved by changing your settings https://stackoverflow.com/questions/44196672/aapt2-compile-failed-invalid-dimen-on-android-3-0-canary-1

**Comment by ronocod** [comment]
Fixed in 3.2.4.

**Comment by yduman** [comment]
The problem still occurs in Canary Version 3, with the same logs

**Comment by LeadManPL** [comment]
AS 3.0 Beta 2 still has this issue

**Comment by ronocod** [comment]
@LeadManPL what version of the SDK are you using, and can you paste the full error message you're seeing here?

**Comment by LeadManPL** [comment]
@ronocod I just read, that it is well known bug in Android Studio 3.0 AAPT:
https://issuetracker.google.com/issues/64962882
Sorry for disturbance...
