### ISSUE TITLE
CredentialStore NPE

### ISSUE THREAD

**Issue by PaNaVTEC** [intercom/intercom-android#45]
```
java.lang.NullPointerException
       at intercom.intercomsdk.credentialstore.CredentialStore.isLoggedInUser(:338)
       at intercom.intercomsdk.ViewManagers.ComposerManager.createConversationUI(:595)
       at intercom.intercomsdk.ViewManagers.ComposerManager.restoreMessageList(:238)
       at intercom.intercomsdk.ViewManagers.ComposerManager.setupWithConversation(:747)
       at intercom.intercomsdk.ViewManagers.ComposerManager.getFullConversationSuccess(:768)
       at intercom.intercomsdk.fragment.ComposerHeadlessFragment$2.onResponse(:114)
       at intercom.intercomsdk.fragment.ComposerHeadlessFragment$2.onResponse(:111)
       at intercom.intercomsdk.api.Engine$11.onResponse(:593)
       at intercom.intercomsdk.api.Engine$11.onResponse(:590)
       at intercom.intercomsdk.api.GsonRequest.deliverResponse(:82)
       at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(:99)
       at android.os.Handler.handleCallback(Handler.java:605)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4511)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:980)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:747)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by Harkin** [comment]
Hey thanks for logging this with us. I've moved it to our internal tracker. We're working on a new release for the private beta and I'm confidant that we've addressed this one :)

**Comment by joshln87** [comment]
Still facing this crash with 0.8.5.. Any fix in the next release?

**Comment by Harkin** [comment]
@joshln87 yeah we've addressed this one, the next release will have a fix
